version: "3.9"

services:
  web:
    build:
      context: ./vai_paqueta_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./vai_paqueta_backend/.env
    volumes:
      - ./vai_paqueta_backend/db.sqlite3:/app/db.sqlite3
    restart: unless-stopped
