version: "3.9"

services:
  web:
    build:
      context: ./vai_paqueta_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./vai_paqueta_backend/.env
    environment:
      - DJANGO_DB_PATH=/app/data/db.sqlite3
    volumes:
      - db_data:/app/data
      - staticfiles:/app/staticfiles
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - staticfiles:/static:ro
    restart: unless-stopped

volumes:
  db_data:
  staticfiles:
