name: vai_paqueta_app
description: Aplicativo Flutter para o EcoTaxi "Vai PaquetÃ¡".
publish_to: "none"
version: 1.0.0+8

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  dio: ^5.5.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  geolocator: ^11.1.0
  uuid: ^4.4.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_tile_caching: ^9.0.0
  url_launcher: ^6.3.0
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/
    - assets/addresses.json
    - assets/logo/
